const mongoose = require("mongoose");
const Job = require("./models/Job");
require("dotenv").config();

const jobs = [
  { title: "Frontend Developer", company: "Google", location: "Bangalore", salary: 120000, skills: ["React", "CSS"], branch: "CSE" },
  { title: "Backend Developer", company: "Google", location: "Hyderabad", salary: 130000, skills: ["Node.js", "MongoDB"], branch: "CSE" },
  { title: "SRE Engineer", company: "Google", location: "Pune", salary: 145000, skills: ["Kubernetes", "Go"], branch: "CSE" },
  { title: "Data Scientist", company: "Google", location: "Bangalore", salary: 155000, skills: ["Python", "TensorFlow"], branch: "CSE" },
  { title: "Data Analyst", company: "Microsoft", location: "Pune", salary: 100000, skills: ["Python", "Excel"], branch: "IT" },
  { title: "Cloud Engineer", company: "Microsoft", location: "Noida", salary: 115000, skills: ["Azure", "Docker"], branch: "CSE" },
  { title: "Software Engineer", company: "Microsoft", location: "Hyderabad", salary: 125000, skills: ["C#", ".NET"], branch: "CSE" },
  { title: "AI Researcher", company: "Microsoft", location: "Bangalore", salary: 160000, skills: ["Python", "PyTorch"], branch: "CSE" },
  { title: "ML Engineer", company: "Amazon", location: "Bangalore", salary: 140000, skills: ["Python", "TensorFlow"], branch: "CSE" },
  { title: "DevOps Engineer", company: "Amazon", location: "Chennai", salary: 125000, skills: ["AWS", "Jenkins"], branch: "IT" },
  { title: "SDE-1", company: "Amazon", location: "Hyderabad", salary: 135000, skills: ["Java", "Spring Boot"], branch: "CSE" },
  { title: "SDE-2", company: "Amazon", location: "Bangalore", salary: 180000, skills: ["Java", "Kafka"], branch: "CSE" },
  { title: "Android Developer", company: "Infosys", location: "Mumbai", salary: 90000, skills: ["Java", "Kotlin"], branch: "CSE" },
  { title: "Java Developer", company: "Infosys", location: "Pune", salary: 85000, skills: ["Java", "Spring"], branch: "CSE" },
  { title: "UI/UX Designer", company: "Infosys", location: "Bangalore", salary: 88000, skills: ["Figma", "Adobe XD"], branch: "Design" },
  { title: "UI/UX Designer", company: "Wipro", location: "Delhi", salary: 85000, skills: ["Figma", "Adobe XD"], branch: "Design" },
  { title: "QA Engineer", company: "Wipro", location: "Chennai", salary: 80000, skills: ["Selenium", "JIRA"], branch: "IT" },
  { title: "SAP Consultant", company: "Wipro", location: "Bangalore", salary: 95000, skills: ["SAP", "ABAP"], branch: "IT" },
  { title: "Full Stack Developer", company: "TCS", location: "Kolkata", salary: 95000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "Business Analyst", company: "TCS", location: "Mumbai", salary: 88000, skills: ["Excel", "SQL"], branch: "IT" },
  { title: "System Engineer", company: "TCS", location: "Chennai", salary: 82000, skills: ["Java", "Linux"], branch: "CSE" },
  { title: "Cybersecurity Analyst", company: "HCL", location: "Bangalore", salary: 110000, skills: ["Networking", "Linux"], branch: "IT" },
  { title: "Network Engineer", company: "HCL", location: "Noida", salary: 95000, skills: ["CCNA", "Cisco"], branch: "ECE" },
  { title: "iOS Developer", company: "Apple", location: "Hyderabad", salary: 145000, skills: ["Swift", "Xcode"], branch: "CSE" },
  { title: "macOS Engineer", company: "Apple", location: "Bangalore", salary: 150000, skills: ["Swift", "Objective-C"], branch: "CSE" },
  { title: "Software Engineer", company: "Meta", location: "Bangalore", salary: 160000, skills: ["React", "GraphQL"], branch: "CSE" },
  { title: "AR/VR Developer", company: "Meta", location: "Hyderabad", salary: 155000, skills: ["Unity", "C#"], branch: "CSE" },
  { title: "Data Scientist", company: "Netflix", location: "Mumbai", salary: 150000, skills: ["Python", "Spark"], branch: "CSE" },
  { title: "Streaming Engineer", company: "Netflix", location: "Bangalore", salary: 145000, skills: ["Java", "Kafka"], branch: "CSE" },
  { title: "Site Reliability Engineer", company: "Twitter", location: "Pune", salary: 135000, skills: ["Kubernetes", "Go"], branch: "CSE" },
  { title: "Backend Engineer", company: "Uber", location: "Bangalore", salary: 140000, skills: ["Java", "Kafka"], branch: "CSE" },
  { title: "Maps Engineer", company: "Uber", location: "Hyderabad", salary: 138000, skills: ["Python", "C++"], branch: "CSE" },
  { title: "Data Engineer", company: "Flipkart", location: "Bangalore", salary: 120000, skills: ["Spark", "Hadoop"], branch: "IT" },
  { title: "Backend Developer", company: "Flipkart", location: "Bangalore", salary: 125000, skills: ["Java", "MySQL"], branch: "CSE" },
  { title: "Product Engineer", company: "Swiggy", location: "Bangalore", salary: 115000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "Logistics Engineer", company: "Swiggy", location: "Hyderabad", salary: 110000, skills: ["Python", "Go"], branch: "CSE" },
  { title: "Platform Engineer", company: "Zomato", location: "Delhi", salary: 110000, skills: ["Python", "Django"], branch: "CSE" },
  { title: "Growth Engineer", company: "Zomato", location: "Bangalore", salary: 108000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "Software Developer", company: "Paytm", location: "Noida", salary: 105000, skills: ["Java", "Spring"], branch: "CSE" },
  { title: "Payments Engineer", company: "Paytm", location: "Delhi", salary: 112000, skills: ["Node.js", "Redis"], branch: "CSE" },
  { title: "Cloud Architect", company: "IBM", location: "Bangalore", salary: 130000, skills: ["AWS", "Terraform"], branch: "CSE" },
  { title: "Blockchain Developer", company: "IBM", location: "Pune", salary: 128000, skills: ["Hyperledger", "Go"], branch: "CSE" },
  { title: "Systems Engineer", company: "Oracle", location: "Hyderabad", salary: 100000, skills: ["SQL", "Java"], branch: "CSE" },
  { title: "Database Engineer", company: "Oracle", location: "Bangalore", salary: 115000, skills: ["Oracle DB", "PL/SQL"], branch: "CSE" },
  { title: "Network Engineer", company: "Cisco", location: "Bangalore", salary: 108000, skills: ["Networking", "CCNA"], branch: "ECE" },
  { title: "Embedded Engineer", company: "Qualcomm", location: "Hyderabad", salary: 125000, skills: ["C", "Embedded Systems"], branch: "ECE" },
  { title: "5G Engineer", company: "Qualcomm", location: "Bangalore", salary: 130000, skills: ["RF", "Signal Processing"], branch: "ECE" },
  { title: "VLSI Engineer", company: "Intel", location: "Bangalore", salary: 130000, skills: ["VHDL", "Verilog"], branch: "ECE" },
  { title: "CPU Architect", company: "Intel", location: "Hyderabad", salary: 145000, skills: ["Computer Architecture", "C++"], branch: "ECE" },
  { title: "Frontend Engineer", company: "Adobe", location: "Noida", salary: 118000, skills: ["JavaScript", "TypeScript"], branch: "CSE" },
  { title: "Creative Engineer", company: "Adobe", location: "Bangalore", salary: 122000, skills: ["React", "WebGL"], branch: "CSE" },
  { title: "ML Researcher", company: "Samsung", location: "Bangalore", salary: 122000, skills: ["Python", "PyTorch"], branch: "CSE" },
  { title: "Embedded Software Engineer", company: "Samsung", location: "Noida", salary: 110000, skills: ["C++", "Linux"], branch: "ECE" },
  { title: "Software Engineer", company: "Accenture", location: "Mumbai", salary: 88000, skills: ["Java", ".NET"], branch: "IT" },
  { title: "Cloud Consultant", company: "Accenture", location: "Bangalore", salary: 92000, skills: ["AWS", "Azure"], branch: "IT" },
  { title: "Consultant", company: "Deloitte", location: "Delhi", salary: 92000, skills: ["SAP", "Excel"], branch: "IT" },
  { title: "Tech Analyst", company: "Deloitte", location: "Mumbai", salary: 96000, skills: ["Python", "Tableau"], branch: "IT" },
  { title: "Technology Analyst", company: "Cognizant", location: "Chennai", salary: 85000, skills: ["Java", "SQL"], branch: "IT" },
  { title: "Associate Engineer", company: "Capgemini", location: "Pune", salary: 82000, skills: ["Python", "AWS"], branch: "CSE" },
  { title: "Graduate Engineer", company: "L&T Technology", location: "Bangalore", salary: 80000, skills: ["AutoCAD", "MATLAB"], branch: "Mechanical" },
  { title: "Software Engineer", company: "Zoho", location: "Chennai", salary: 90000, skills: ["Java", "React"], branch: "CSE" },
  { title: "Product Developer", company: "Zoho", location: "Chennai", salary: 95000, skills: ["Python", "Django"], branch: "CSE" },
  { title: "Backend Developer", company: "Freshworks", location: "Chennai", salary: 105000, skills: ["Ruby", "Rails"], branch: "CSE" },
  { title: "Frontend Engineer", company: "Freshworks", location: "Bangalore", salary: 108000, skills: ["React", "TypeScript"], branch: "CSE" },
  { title: "SDE", company: "Razorpay", location: "Bangalore", salary: 130000, skills: ["Node.js", "PostgreSQL"], branch: "CSE" },
  { title: "Payments Engineer", company: "Razorpay", location: "Bangalore", salary: 135000, skills: ["Java", "Kafka"], branch: "CSE" },
  { title: "Software Engineer", company: "CRED", location: "Bangalore", salary: 135000, skills: ["Kotlin", "Go"], branch: "CSE" },
  { title: "Data Analyst", company: "PhonePe", location: "Bangalore", salary: 112000, skills: ["SQL", "Tableau"], branch: "IT" },
  { title: "SDE", company: "PhonePe", location: "Bangalore", salary: 125000, skills: ["Java", "Spring Boot"], branch: "CSE" },
  { title: "SDE", company: "Meesho", location: "Bangalore", salary: 118000, skills: ["Java", "Spring Boot"], branch: "CSE" },
  { title: "Growth Engineer", company: "Meesho", location: "Bangalore", salary: 115000, skills: ["Python", "React"], branch: "CSE" },
  { title: "Engineer", company: "Ola", location: "Bangalore", salary: 108000, skills: ["Python", "Kafka"], branch: "CSE" },
  { title: "Maps Engineer", company: "Ola", location: "Hyderabad", salary: 112000, skills: ["C++", "Python"], branch: "CSE" },
  { title: "Software Developer", company: "Byju's", location: "Bangalore", salary: 95000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "SDE", company: "Nykaa", location: "Mumbai", salary: 100000, skills: ["Java", "MySQL"], branch: "CSE" },
  { title: "SDE", company: "Myntra", location: "Bangalore", salary: 118000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "Recommendation Engineer", company: "Myntra", location: "Bangalore", salary: 125000, skills: ["Python", "ML"], branch: "CSE" },
  { title: "Software Engineer", company: "Atlassian", location: "Bangalore", salary: 140000, skills: ["Java", "Python"], branch: "CSE" },
  { title: "DevOps Engineer", company: "Atlassian", location: "Bangalore", salary: 135000, skills: ["Docker", "Kubernetes"], branch: "CSE" },
  { title: "SDE", company: "Groww", location: "Bangalore", salary: 125000, skills: ["Java", "React"], branch: "CSE" },
  { title: "Data Engineer", company: "Groww", location: "Bangalore", salary: 120000, skills: ["Python", "Spark"], branch: "CSE" },
  { title: "Backend Engineer", company: "Dream11", company: "Dream11", location: "Mumbai", salary: 130000, skills: ["Go", "Redis"], branch: "CSE" },
  { title: "Platform Engineer", company: "Dream11", location: "Mumbai", salary: 128000, skills: ["Java", "Kafka"], branch: "CSE" },
  { title: "SDE", company: "Zerodha", location: "Bangalore", salary: 120000, skills: ["Python", "Go"], branch: "CSE" },
  { title: "Quant Developer", company: "Zerodha", location: "Bangalore", salary: 135000, skills: ["Python", "C++"], branch: "CSE" },
  { title: "Software Engineer", company: "Postman", location: "Bangalore", salary: 130000, skills: ["Node.js", "React"], branch: "CSE" },
  { title: "SDE", company: "BrowserStack", location: "Mumbai", salary: 125000, skills: ["Java", "Selenium"], branch: "CSE" },
  { title: "Software Engineer", company: "Chargebee", location: "Chennai", salary: 115000, skills: ["Ruby", "React"], branch: "CSE" },
  { title: "SDE", company: "Darwinbox", location: "Hyderabad", salary: 110000, skills: ["Java", "Angular"], branch: "CSE" },
  { title: "ML Engineer", company: "Sarvam AI", location: "Bangalore", salary: 140000, skills: ["Python", "LLMs"], branch: "CSE" },
  { title: "AI Engineer", company: "Sarvam AI", location: "Bangalore", salary: 145000, skills: ["Python", "NLP"], branch: "CSE" },
  { title: "Software Engineer", company: "Sprinklr", location: "Gurgaon", salary: 118000, skills: ["Java", "React"], branch: "CSE" },
  { title: "Data Scientist", company: "Mu Sigma", location: "Bangalore", salary: 105000, skills: ["Python", "R"], branch: "CSE" },
  { title: "Analyst", company: "Mu Sigma", location: "Bangalore", salary: 95000, skills: ["SQL", "Excel"], branch: "IT" },
  { title: "Software Engineer", company: "Tekion", location: "Bangalore", salary: 125000, skills: ["Java", "React"], branch: "CSE" },
  { title: "Firmware Engineer", company: "Texas Instruments", location: "Bangalore", salary: 118000, skills: ["C", "Embedded"], branch: "ECE" },
  { title: "Chip Design Engineer", company: "Texas Instruments", location: "Hyderabad", salary: 122000, skills: ["Verilog", "VLSI"], branch: "ECE" },
  { title: "Software Engineer", company: "Salesforce", location: "Hyderabad", salary: 135000, skills: ["Java", "Apex"], branch: "CSE" },
  { title: "MTS Engineer", company: "Salesforce", location: "Bangalore", salary: 140000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "SDE", company: "Juspay", location: "Bangalore", salary: 120000, skills: ["Haskell", "Node.js"], branch: "CSE" },
  { title: "Software Engineer", company: "ShareChat", location: "Bangalore", salary: 125000, skills: ["Go", "Python"], branch: "CSE" },
  { title: "ML Engineer", company: "ShareChat", location: "Bangalore", salary: 130000, skills: ["Python", "PyTorch"], branch: "CSE" },
  { title: "Software Engineer", company: "Turing", location: "Remote", salary: 150000, skills: ["React", "Node.js"], branch: "CSE" },
  { title: "Backend Engineer", company: "Turing", location: "Remote", salary: 155000, skills: ["Python", "Django"], branch: "CSE" },
  { title: "Graduate Engineer Trainee", company: "BHEL", location: "Delhi", salary: 65000, skills: ["AutoCAD", "MATLAB"], branch: "Mechanical" },
  { title: "Junior Engineer", company: "NTPC", location: "Delhi", salary: 70000, skills: ["Electrical", "AutoCAD"], branch: "Electrical" },
  { title: "Graduate Engineer", company: "ONGC", location: "Mumbai", salary: 75000, skills: ["Petroleum", "AutoCAD"], branch: "Mechanical" },
  { title: "IT Officer", company: "SBI", location: "Mumbai", salary: 72000, skills: ["Java", "SQL"], branch: "IT" },
  { title: "Software Engineer", company: "Nagarro", location: "Gurgaon", salary: 100000, skills: ["React", "Java"], branch: "CSE" },
  { title: "Associate Consultant", company: "PwC", location: "Mumbai", salary: 98000, skills: ["Python", "SQL"], branch: "IT" },
  { title: "Technology Analyst", company: "EY", location: "Bangalore", salary: 95000, skills: ["Java", "AWS"], branch: "CSE" },
  { title: "Analyst", company: "KPMG", location: "Delhi", salary: 92000, skills: ["SQL", "Tableau"], branch: "IT" }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected ✅");
    await Job.deleteMany({});
    console.log("Old jobs cleared 🗑️");
    await Job.insertMany(jobs);
    console.log(`${jobs.length} jobs inserted ✅`);
    mongoose.connection.close();
    console.log("Done! Now run npm run dev 🚀");
  } catch (err) {
    console.error("Error:", err);
  }
}

seed();
